### PR TITLE
Project as query params of login URL

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

https://user-images.githubusercontent.com/32532742/135324957-6db5d40c-b8ad-4f73-9a72-2639e5e10323.mp4

**Which issue(s) this PR fixes**:

Fixes https://github.com/pipe-cd/pipe/issues/1590

**Does this PR introduce a user-facing change?**:

```release-note
Enable to specific project to login to by project query params in the URL
```

### CODE REVIEW

**Comment by nakabonne** [comment]
Thank you! It solves https://github.com/pipe-cd/pipe/issues/1590 so I updated the PR description.

**Comment by nakabonne** [comment]
Also, it's obviously a user-facing change, so can you write what's changed in the PR description?

**Comment by khanhtc1202** [comment]
> Thank you! It solves https://github.com/pipe-cd/pipe/issues/1590 so I updated the PR description.

oh I didn't know about that issue, thanks. Btw, we have a way to avoid that issue by access `/login/{project}` but its kind of tricky and hard to realize 😄
By this PR, I disabled that `/login/{project}` path too.

**Comment by nghialv** [comment]
Really cool. Thank you.
/approve

**Pull request merged**
