### PR TITLE
Refactor components directory structure

### PR DESCRIPTION
**Pull request by cakecatz**
**What this PR does / why we need it**:

Use `src/components` as shared components directory.
If the page has page-specific component, put the file to `page-name/components/` directory.
This will make more clarify component’s dependencies.

## Before

```
components/
├─ common-component/
├─ used-by-comp-A/
├─ used-by-login-page/
├─ comp-A/
pages/
├─ login-page/
└─ detail-page/
```

## After

```
components/
├─ common-component/
├─ comp-A/
│  └─ used-by-comp-A/
pages/
├─ login-page/
│  └─ components/
│     └─ used-by-login-page/
└─ detail-page/

```

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
I'm not sure but how about this: merging `pages` into `compoments`, page component will be suffixed by `page`.

```
components/
├─ common-component/
├─ comp-A/
│  └─ used-by-comp-A/
├─ login-page/
│  └─ components/
│     └─ used-by-login-page/
└─ detail-page/
```

**Comment by cakecatz** [comment]
@nghialv In fact, since page-component is just a component, I think it's a good idea to put it in the component directory as you commented. 👍

**Comment by nghialv** [comment]
Thank you. I think so too.

**Comment by khanhtc1202** [comment]
thx 🚀 
/approve

**Pull request merged**
