### PR TITLE
Rename pkg/app/api package to pkg/app/server

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

This PR renamed `pkg/app/api` package to `pkg/app/server` since we already merged "api" component to a new "server" component before.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Hold until the release of `v0.24.0`.

**Comment by nghialv** [comment]
This is fine to merge before the new release of `v0.24.0` so I am going to remove the `hold` label.

**Comment by khanhtc1202** [comment]
Nice, let's give it a shot 👍 
/lgtm

**Comment by nakabonne** [comment]
This makes sense to everyone.
/approve

**Pull request merged**
