### PR TITLE
Always add project as pipecd URL query params

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
I just tried using this on my local and it seems that the logout functionality is not working.

**Comment by nghialv** [comment]
Ah, maybe that is the problem of our local behavior not because of this change.
The local is using a cookie that was specified in a local file so it was not removed while logging out.

**Comment by nghialv** [comment]
If so, I guess we have to merge this to check the logout behavior, right?

**Comment by khanhtc1202** [comment]
> If so, I guess we have to merge this to check the logout behavior, right?

yes, you're right. The local use specificed cookie to to so login/logout feature are not working.

**Comment by nghialv** [comment]
This still allows the path without a project parameter, right?
Because I think we are generating some web URLs at Piped for some places such as links in the notification.

**Comment by khanhtc1202** [comment]
> This still allows the path without a project parameter, right?
> 
> Because I think we are generating some web URLs at Piped for some places such as links in the notification.

yes, it is. Since I only add a query params to the URL but not change anything in the routing logic, all URL with/without that query params should work fine.

**Comment by nghialv** [comment]
> all URL with/without that query params should work fine.

Nice.

**Comment by nghialv** [comment]
Ok. This will allow specifying the project name in the login path and will be useful in the future when we support logging into multiple projects at the same time.
/lgtm

**Comment by khanhtc1202** [comment]
> This will allow specifying the project name in the login path

Will make PR for this after this one got merged 😄

**Comment by nakabonne** [comment]
Way to go 👍 
/approve

**Pull request merged**
