### PR TITLE
Add mentions to trigger deployment failed notification

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ono-max** [comment]
Wow, nice idea 👍 
/lgtm

**Comment by nakabonne** [comment]
Nice. Do we need to address the case of `NotificationEventDeploymentRollingBack` as well?

**Comment by nakabonne** [comment]
In either way, it is able to fall into another PR.

**Comment by khanhtc1202** [comment]
> Nice. Do we need to address the case of `NotificationEventDeploymentRollingBack` as well?

Not yet, since we do not return that event anywhere. Should make a separated PR for that (include where we will notify that event to slack) cc @ono-max

**Comment by nakabonne** [comment]
Alright 👍 
/approve

**Pull request merged**
