### PR TITLE
Propagate stop signal properly

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/pipe-cd/pipe/issues/1134

**Does this PR introduce a user-facing change?**:

```release-note
Fix a bug that it was unable to cancel during performing ADA stage
```

### CODE REVIEW

**Comment by nghialv** [comment]
The PR title will be used for generating the changelog, so I think it should be
"Fix a bug that it was unable to rollback .."
It helps our users to quickly know what was fixed when they see the changelog.

/lgtm

**Comment by nakabonne** [comment]
I'd like to explicitly distinguish the commit message and the changelog for end-users, so updated the changelog section in this PR body. I feel It's enough but is it ok?

**Comment by nghialv** [comment]
Yes, the changelog section was created for that case. 👍

**Comment by khanhtc1202** [comment]
nits,
> Fix unable to cancel during performing ADA stage

👍

**Pull request merged**
