### PR TITLE
Enable insights tab on header

### LINKED ISSUE #1257: Restore a link to the insights in the v1 release
https://github.com/pipe-cd/pipe/blob/f4ce9463ec76a72e2f716c898237f26315cd731e/pkg/app/web/src/components/header.tsx#L126-L129

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1257

**Does this PR introduce a user-facing change?**:

```release-note
Enable insights tab on header
```

### CODE REVIEW

**Comment by nakabonne** [comment]
If I understand right, it's not available yet. We can access the page by typing path manually, but tell me why it's needed.

**Comment by khanhtc1202** [comment]
> If I understand right, it's not available yet. We can access the page by typing path manually, but tell me why it's needed.

Sorry for not clarify the context of this change 🙏  We're going to rolling out this feature and just want to make it more friendly to access (click tab on the header). Currently, I'm thinking about move the applications count badges to the insights page too, so make it easier to be accessed would be nice 😄

**Comment by nakabonne** [comment]
Ah, that's what you're trying. Now I got it 👍 
/lgtm

**Comment by khanhtc1202** [comment]
> Ah, that's what you're trying. Now I got it 👍

Yep 🙌  Basically, It will keep its status (not fully available) but will show
- applications count badges (all badges instead of just registered application kind)
- all graphs with text like "Comming soon"

**Comment by nghialv** [comment]
Thank you.
/approve

**Pull request merged**
