### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by masaaania**
**What this PR does / why we need it**:

- Fix typo

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by nakabonne** [comment]
@masaaania Hi, thank you for your contribution! It would be great if you could keep being interested in this project!
/lgtm

**Comment by nghialv** [comment]
@masaaania Nice. Thank you.
/approve

**Pull request merged**
