### PR TITLE
Add filtering for the fetch applications that exclude deleted app

### PR DESCRIPTION
**Pull request by cakecatz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Fix showing deleted app at the application list
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Nice 👍 
/approve

**Comment by cakecatz** [comment]
@khanhtc1202 I added a commit to supports `deleted: undefined`.

**Comment by khanhtc1202** [comment]
Nice, thank you ✨ 
/approve

**Pull request merged**
