### PR TITLE
Hide database migration post from table of content list

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Hide the database migration post from blog table of content, since that version is staled and we're not going to support that migration script in the future.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
This is a blog post, not documentation. I feel like you basically shouldn't delete it once you publish it as someone is still likely to refer to this page even if it gets outdated.

**Comment by nakabonne** [comment]
I don't have a strong opinion so if you guys are fine, proceed as is.

**Comment by khanhtc1202** [comment]
> This is a blog post, not documentation. I feel like you basically shouldn't delete it once you publish it even if it gets outdated as someone is still likely to refer to this page.

I feel you, but the change I made here does not delete the post content. It's possible to access the post by URL directly, just hide it from the table of content list, since migration post may cause users to misunderstand that our PipeCD highly depends on a database, that may not good for the product image.

**Comment by nakabonne** [comment]
That makese total sense. In that case fine to me 👍 
There you go /approve

**Review by nakabonne — APPROVED** [review]

**Pull request merged**
