### PR TITLE
Show promote percentage on the stage

### LINKED ISSUE #1538: Show promote detail to PipelineStage badge for CloudRun/Lambda application
**What would you like to be added**:

- Implement UI

**Why is this needed**:

ref #1461

### PR DESCRIPTION
**Pull request by cakecatz**
**What this PR does / why we need it**:

image

**Which issue(s) this PR fixes**:

Fixes #1538

**Does this PR introduce a user-facing change?**:

```release-note
Show promote percentage on the stage
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Cool ✨ 
/lgtm

**Comment by nghialv** [comment]
How about using the same format with K8s "Primary 90%, Canary 10%"?

**Comment by nghialv** [comment]
I noticed that primary/canary will be hard to understand for this promote stage. So maybe "50% promoted" looks better.

**Comment by khanhtc1202** [comment]
> I noticed that primary/canary will be hard to understand for this promote stage. So maybe "50% promoted" looks better.

**Comment by cakecatz** [comment]
@nghialv It sure looks good.

Updated displaying metadata.

image

**Comment by nghialv** [comment]
Thanh you.
/approve

**Pull request merged**
