### PR TITLE
Fix bundling web resources

### PR DESCRIPTION
**Pull request by cakecatz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
> Fix some pages that were blank.

I think this bug has not appeared in the released version so no need to add this note 🤔

**Comment by nghialv** [comment]
> I think this bug has not appeared in the released version so no need to add this note 🤔

Agree.

**Comment by khanhtc1202** [comment]
Thanks 🙏 
/lgtm

**Pull request merged**
