### PR TITLE
Move Application count badges to Insights page

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

https://user-images.githubusercontent.com/32532742/130216930-9c0eb7f6-0f59-419c-b53e-f3ec92ed4bcb.mp4

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Move application count badges to Insights page
```

### CODE REVIEW

**Comment by nghialv** [comment]
Nice. You made my day!
/approve

**Review by nghialv — APPROVED** [review]

**Comment by nghialv** [comment]
Oops, the web-test failed.

**Comment by khanhtc1202** [comment]
> Oops, the web-test failed.

Yep, it's my miss, just updated the failed test 🙏

**Pull request merged**
