### PR TITLE
Add piped dashboards provider to Grafana config

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
You also have to add a ConfigMap like:
https://github.com/pipe-cd/pipe/blob/5e42e11f2aec83fdf2757ad5b4ecf72147799ded/manifests/pipecd/templates/configmap.yaml#L17-L48

**Comment by khanhtc1202** [comment]
Thx @nakabonne, updated PTAL 👀

**Comment by nakabonne** [comment]
Nice
/lgtm

**Pull request merged**
