### PR TITLE
Add admissionregistration.k8s.io/* API to the default watching list of Kubernetes

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes part of #2436

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ono-max** [comment]
@nghialv 

Sorry, I found mistake in my commit message and fixed it. Could you type "lgtm" again?

**Comment by nghialv** [comment]
Yes. 👍 
/lgtm

**Comment by nakabonne** [comment]
Nice, but seems like it has conflicts 👀

**Comment by khanhtc1202** [comment]
@ono-max this one has conflicts again 👀

**Comment by nghialv** [comment]
Thank you.
/approve

**Pull request merged**
