### PR TITLE
Disable to update application info via the web UI

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:
In order to make the application config defined in Git a single source of truth, we need to make it impossible to update anything other than Piped and Cloud Provider from the web.

image

**Which issue(s) this PR fixes**:

Close https://github.com/pipe-cd/pipe/issues/2778

**Does this PR introduce a user-facing change?**:

```release-note
Updating application information via the Web UI is no longer possible
```

### CODE REVIEW

**Comment by nghialv** [comment]
Great! Finally, we can disable those operations.

/approve

**Comment by nakabonne** [comment]
web-test failed

**Comment by nakabonne** [comment]
@nghialv Let me comment out the failed test for now case as I couldn't figure out why it failed. I'm going to ask @khanhtc1202 then I would fix and revert it.

**Comment by nghialv** [comment]
Sure.
/approve

**Comment by nakabonne** [comment]
What the yarn versions between local and CI are different confuses me always.

**Comment by nakabonne** [comment]
>yarn run v1.19.1

I wonder why the version yarn on CI is v1.19.1 even though it's fixed by bazel: https://github.com/pipe-cd/pipe/blob/f927e576cb5fddd7fe99d9275c8837b7990939b2/WORKSPACE#L197

**Pull request merged**
