### PR TITLE
Add docs on pipectl available commands

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:
Fix `pipectl --help` and `pipectl application add --help` output result.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
plz add `NONE` to the place under "Does this PR introduce a user-facing change?" title in the PR description.

**Comment by nakabonne** [comment]
@knanao Good catch! Sorry for confusing you but all under the `/docs` directory will be overridden; thus can you update ones under `/docs-dev`?

**Comment by knanao** [comment]
@khanhtc1202 @nakabonne 
thx for your reviews!! plz check fixes.

**Comment by nakabonne** [comment]
Thanks, keep it up!
/lgtm

**Comment by nghialv** [comment]
Nice. Thank you.
/approve

**Pull request merged**
