### PR TITLE
Bump Prometheus client to v1.11.0

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:
I've checked it doesn't have any kind of negative impact on PipeCD.

- https://github.com/prometheus/client_golang/releases
- https://github.com/protocolbuffers/protobuf-go/releases

Also, I've checked that metrics exposing goes well locally.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Should we seperate protobuf version update with this prometheous version update PR. 👀

**Comment by nakabonne** [comment]
Truthfully, I want to do so, but `go mod tidy` doesn't allow us it.

**Comment by nghialv** [comment]
@khanhtc1202 Where are you now? Sent your comment from Hokaido? 😄

**Comment by nghialv** [comment]
Nice.
It looks fine for other updates as well.
/approve

**Comment by khanhtc1202** [comment]
> @khanhtc1202 Where are you now? Sent your comment from Hokaido? 😄 

yeh, I'm super bored in a running bus near by Sapporo 🙈

**Comment by nakabonne** [comment]
>@khanhtc1202 Where are you now? Sent your comment from Hokaido? 😄

Seriously? 🙄

**Comment by khanhtc1202** [comment]
> >@khanhtc1202 Where are you now? Sent your comment from Hokaido? 😄
> 
> 
> 
> Seriously? 🙄 

yep 🙌

**Pull request merged**
