### PR TITLE
Update examples in doc for secret management feature

### PR DESCRIPTION
**Pull request by ww24**
**What this PR does / why we need it**:

Update manifest examples to valid YAML format.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Thanks for contribution 🙌 
Please use "NONE" for "Does this PR introduce a user-facing change?:" note, since this PR only change the docs, not the feature behavior itself 🙏

**Comment by nghialv** [comment]
Thank you for your pull request.
Nice catch!
/approve

**Pull request merged**
