### PR TITLE
Add release panel to ja docs

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

- Add release panel to JA docs
- Update `make site` command reflect change

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
It doesn't work fine on my laptop. 
```
❯ make site
env RELEASE=v0.10.2 hugo server --source=docs
Building sites … ERROR 2021/06/29 11:35:43 [en] REF_NOT_FOUND: Ref "/docs/quickstart/": "/Users/s07726/src/github.com/pipe-cd/pipe/docs/content/en/_index.html:1:1": page not found
Built in 1415 ms
Error: Error building site: logged 1 error(s)
make: *** [site] Error 255
```

@khanhtc1202 did it go well on your environment?

**Comment by khanhtc1202** [comment]
> It doesn't work fine on my laptop.
> 
> ```
> ❯ make site
> env RELEASE=v0.10.2 hugo server --source=docs
> Building sites … ERROR 2021/06/29 11:35:43 [en] REF_NOT_FOUND: Ref "/docs/quickstart/": "/Users/s07726/src/github.com/pipe-cd/pipe/docs/content/en/_index.html:1:1": page not found
> Built in 1415 ms
> Error: Error building site: logged 1 error(s)
> make: *** [site] Error 255
> ```
> 
> @khanhtc1202 did it go well on your environment?

Sure 👀 The error showed that you don't have `docs/quickstart` even for `en` version of the documentation, that's weird 🤔
Could you checkout master and rerun the command 🙏

**Comment by nakabonne** [comment]
for sure. It doesn't work even at the master branch.

```
pipe on ᚠ master [$] took 2m42s
❯ make site
hugo server --source=docs
Building sites … ERROR 2021/06/29 11:41:40 [en] REF_NOT_FOUND: Ref "/docs/quickstart/": "/Users/s07726/src/github.com/pipe-cd/pipe/docs/content/en/_index.html:1:1": page not found
```

**Comment by nakabonne** [comment]
okay, let me approve it as it turns out my own issue
/approve

**Comment by khanhtc1202** [comment]
> okay, let me approve it as it turns out my own issue
> /approve

thx 🙏

**Comment by nakabonne** [comment]
>for sure. It doesn't work even at the master branch.

That was because hugo that I'm using is too old

```
❯ hugo version
Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown
```

Updating did fix it.

**Pull request merged**
