### PR TITLE
Add the explanation to the document to make it easier to understand

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:
I added the explanation to the document. Hopefully, this change will be more friendly for users.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:
 
```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Nice adding. Thank you.
/lgtm

**Comment by khanhtc1202** [comment]
🚀 
/approve

**Comment by nakabonne** [comment]
@ono-max Welcome to the PipeCD community! It would be great if you could work on various kinds of issues and learn as many as possible.

**Pull request merged**
