### PR TITLE
Disable deployed by and running commit cols on small screen

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

https://user-images.githubusercontent.com/32532742/149277181-9ab36aaf-7ce7-4da8-8206-b51dc02424a4.mp4

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
I think "Deployed By" should be hidden rather than "Environment" because "Environment is more important.
But want to hear more thoughts from you guys.

**Comment by nakabonne** [comment]
>I think "Deployed By" should be hidden rather than "Environment" because "Environment is more important.

I feel the same way.

**Comment by nakabonne** [comment]
I'm guessing that `Running Commit`, `Deployed by`, and `Deployed at` are less important.

**Comment by khanhtc1202** [comment]
Okay, then lets me adopt you guys suggestion 👍

**Comment by khanhtc1202** [comment]
@nghialv @nakabonne updated, ptal
Screen Shot 2022-01-13 at 17 17 08

**Comment by nghialv** [comment]
Thank you.
/lgtm

**Comment by nakabonne** [comment]
Awesome!
/approve

**Pull request merged**
