### PR TITLE
Fix diff description and image

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:
Fix diff description and image for "Configuration drift detection" docs.

Screen Shot 2022-01-12 at 16 30 27

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Nice catch!
/approve

**Comment by nghialv** [comment]
Could you update the following files too?

https://github.com/pipe-cd/pipe/blob/master/docs/content/en/docs/user-guide/configuration-drift-detection.md
https://github.com/pipe-cd/pipe/blob/master/docs/content/en/docs-v0.23.x/user-guide/configuration-drift-detection.md

**Comment by knanao** [comment]
Is it correct that `docs/*` is applied to all version docs?
If so, should I just fix only the `docs/*`?

**Comment by nghialv** [comment]
@knanao `docs/content/en/docs` just refers to the latest stable version. (which is `docs-v0.23.x` currently)
So in it is fine to fix `docs/content/en/docs-v0.23.x`, `docs/content/en/docs` and `docs/content/en/docs-dev` in this case.

**Comment by nghialv** [comment]
Nice catch!
/lgtm

**Comment by knanao** [comment]
Got it! tyvm!🙇

**Comment by khanhtc1202** [comment]
Nice
/approve

**Pull request merged**
