### PR TITLE
Add tests for ensuring kubernetes sync

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:
Generating `pkg/app/piped/executor/mock.go` with Bazel has a cycle import issue (https://github.com/pipe-cd/pipe/issues/820), hence manually generated for now:
```
mockgen -source=./pkg/app/piped/executor/executor.go -destination=./pkg/app/piped/executor/mock.go -package=executor
```

I will add more test cases as another PR if no problem to keep going.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Do we have any better way? (We should avoid using an external command to generate the code and push them to Git)

**Comment by nakabonne** [comment]
The surest way is resolving https://github.com/pipe-cd/pipe/issues/820 at first.

**Comment by nakabonne** [comment]
I'd better address that, wouldn't it?

**Comment by nghialv** [comment]
Yes, let's do it.

**Comment by nakabonne** [comment]
👍

**Comment by nakabonne** [comment]
I noticed no need to use mock for LogPersister, just fake is enough. It doesn't require to check the log output precisely.

**Comment by nakabonne** [comment]
Just now applied it.

**Comment by nghialv** [comment]
Nice.
/approve

**Pull request merged**
