### PR TITLE
Remove pipe prefix from proto definition of model package

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

This is a small step in order to migrate this `pipe` repository to a new `pipecd` repository in the future.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
> But can I confirm one thing? Looks like if we merge this one, piped which be built on local by bazel will not above to connect the dev control-plane (as mentioned by PR #3025 ), should we hold this as we do with PR #3025?

I think this will not break the communication between the old Piped and the Control Plane since it is just updating for the local model, not gRPC definitions. (Underlying, data transferring in gRPC is marked by the field index numbers.)
But to be sure let me do some check after this got merged and deployed on our dev environment.
If something does not work as our expectation I will revert it.

**Comment by nghialv** [comment]
Another way to check this is to compare their generated Go codes.
Let me check it.

**Comment by nghialv** [comment]
It seems fine. I will give it another check once it got merged.

**Comment by khanhtc1202** [comment]
Thanks 👍  Lets merge and check it later
/lgtm

**Comment by nakabonne** [comment]
Let's check other checks after got merged!
/approve

**Pull request merged**
