### PR TITLE
Fix miss kind in docs

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
The two latest ones should be revised as well?

**Comment by nakabonne** [comment]
I'm curious about how we handle this kind of obvious mistake.

**Comment by khanhtc1202** [comment]
> I'm curious about how we handle this kind of obvious mistake.

Well, I can say that, for the miss spell issue like this, we have to update all versions too 😅 let me update it manually, this PR is just to test the `edit this document` feature from our document site.

**Comment by nakabonne** [comment]
Nice
/approve

**Pull request merged**
