### PR TITLE
Remove invalid snippet on the pipectl doc

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Nice catch
/approve

**Comment by khanhtc1202** [comment]
@nakabonne Could you update that change in `/docs` too 😅  Since the PR https://github.com/pipe-cd/pipe/pull/2724 is merged, maybe use sync command would help 😉

**Comment by nakabonne** [comment]
@khanhtc1202 Updated 👍

**Comment by khanhtc1202** [comment]
Thank you
/approve

**Pull request merged**
