### PR TITLE
Fix the bug that default deployment timeout was not configured for all app kinds except Kubernetes

### LINKED ISSUE #1415: The default timeout value of deployment was not configured for CloudRun, Lambda, Terraform
**What happened**:

**What you expected to happen**:

https://github.com/pipe-cd/pipe/pull/1394

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1415

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
https://github.com/pipe-cd/pipe/blob/c137f9e2ef3e5bf3b9393cabad7dac2cace36889/pkg/config/config.go#L196-L206

I think we should update the validate revoke logic too 👀 
At L200, in case `c.spec` could not cast to `validator` type, we ignore it and return no error. In case `LambdaDeployementSpec`, `CloudrunDeploymentSpec`, `TerraformDeploymentSpec` does not satisfy validator interface, error should be raised.

**Comment by nghialv** [comment]
@khanhtc1202 Right. Let me update that part.

**Comment by nghialv** [comment]
@khanhtc1202 Fixed it!

**Comment by khanhtc1202** [comment]
Thank you 😁 
/lgtm

**Review by nakabonne — APPROVED** [review]
Thank you.

**Pull request merged**
