### PR TITLE
Change required role to add/update application from Admin to Editor

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Change required role to add/update application from Admin to Editor
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Way to go 🚀 
/lgtm

**Comment by nakabonne** [comment]
Okay, editors will get allowed to operate to applications. I'd say they are appropriate roles.

OTOH, it's obviously a fatal breaking change. From now on, all editors get a great responsibility. We must add notes on the next changelog (ideally, it should be applied gradually, but well okay as it's still on the alpha stage)

**Comment by nghialv** [comment]
Right. This will be noted as a breaking change. 👍

**Pull request merged**
