### PR TITLE
Release v0.16.0

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
`make prepare-release` is exactly what I wanted.

**Comment by nghialv** [comment]
Great.
/lgtm

**Comment by khanhtc1202** [comment]
🚀 
/approve

**Comment by khanhtc1202** [comment]
> `make prepare-release` is exactly what I wanted.

consider rename it as `make pre-release` since typing `prepare-release` is too long and I'm lazy 😆

**Pull request merged**
