### PR TITLE
Fix wrong name of a terraform example application

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

This wrong name causes a broken link in the README.md of `examples` repository.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Nice catch ⚾ 
/approve

**Comment by khanhtc1202** [comment]
please update links to example applications on the docs too 👀 
https://pipecd.dev/docs/examples/#terraform-applications

**Comment by nghialv** [comment]
Nice catch!
Thank you. Fixed!

**Comment by khanhtc1202** [comment]
Thx 🚀 
/approve

**Pull request merged**
