### PR TITLE
Fix a bug that unspecified users can approve the WAIT_APPROVAL stage

### LINKED ISSUE #2550: Ensure only users which mentioned in the WAIT_APPROVAL approvers are able to approve the stage
**What happened**:

Currently, users who are not be listed in the WAIT_APPROVAL approvers configuration are able to approve the stage.

ref: https://pipecd.dev/docs/user-guide/adding-a-manual-approval/

Note: according to the docs we have
> In case the approvers field was not configured, anyone in the project who has Editor or Admin role can approve the deployment pipeline.

**What you expected to happen**:

In case the approvers field is configured, only people listed in that field are able to approve the stage.

**How to reproduce it**:

**Environment**:
- `piped` version: 0.18.0
- `control-plane` version: 0.18.0
- Others:

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2550

**Does this PR introduce a user-facing change?**:

```release-note
Fix a bug that unspecified users can approve the WAIT_APPROVAL stage
```

### CODE REVIEW

**Comment by nghialv** [comment]
I want to ask that why it worked before and do we need to update for other application kinds too?

**Comment by ono-max** [comment]
Because `MakeInitialStageMetadata` function is not called when `buildProgressivePipeline` function is called.

First, I would like to confirm that [approvers are retrieved from the metadata](https://github.com/pipe-cd/pipe/blob/master/pkg/app/api/grpcapi/web_api.go#L1297) and [approvers are stored in MakeInitialStageMetadata](https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/planner/planner.go#L65).

In my case, `buildProgressivePipeline` function is called as follows:
https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/planner/kubernetes/kubernetes.go#L205

I noticed that `MakeInitialStageMetadata` function is not called then and work it.

**Comment by ono-max** [comment]
@nghialv 

> do we need to update for other application kinds too?

If you are convinced with this change and the reason, I think we need to update them.

**Comment by nghialv** [comment]
Ok. I think that was the problem so let's update other kinds too.

**Comment by ono-max** [comment]
@nghialv 

Updated 👍

**Comment by nghialv** [comment]
Nice catch!
/approve

**Pull request merged**
