### PR TITLE
Fix stuck with an empty view in case of access to an invalid path

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Before

https://user-images.githubusercontent.com/32532742/135503698-07765063-55f3-4ec6-ae13-0ee6efe07340.mp4

After

https://user-images.githubusercontent.com/32532742/135503723-38c07e2d-a433-4376-9afa-1461ef2a32bb.mp4

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Avoid showing an empty view in case of access to an invalid path
```

### CODE REVIEW

**Comment by nghialv** [comment]
Should we redirect to `applications` page or show an error page?

**Comment by khanhtc1202** [comment]
> Should we redirect to `applications` page or show an error page?

I think both are good and reasonable but redirecting is easier since we don't need to implement an error page.

**Comment by nghialv** [comment]
> redirecting is easier since we don't need to implement an error page

Sure. Let's apply this for now.

**Comment by nakabonne** [comment]
Reasonable definitely
/approve

**Pull request merged**
