### PR TITLE
Update actions-plan-preview to use pipectl v0.13.2

### LINKED ISSUE #2308: Update pipectl version to v0.13.2 once it's rolled out.
https://github.com/pipe-cd/pipe/blob/4008309f1faaa03b80ecc47e1e08a0ed92d31a04/dockers/actions-plan-preview/Dockerfile#L5-L8

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2308 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
🚀 
/approve

**Comment by nghialv** [comment]
Holding this to wait for the completion of `v0.13.2` release.

**Pull request merged**
