### PR TITLE
Remove lock file for dependencies of pipecd chart

### PR DESCRIPTION
**Pull request by nakabonne**
**What this PR does / why we need it**:
This PR makes the process to update dependency charts simpler.
In CI step for publishing charts, it runs `helm package` with `--dependency-update`, which automatically generates Chart.lock. Because of that, the only thing that we need to do when updating verion is modifying Chart.yaml.

**Which issue(s) this PR fixes**:

Fixes https://github.com/pipe-cd/pipe/issues/1863

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
`Chart.lock` is still good for locking our dependencies. 
So if we remove it, let fix our dependencies to specific versions instead of version ranges to avoid implicit updates.

`  version: "~v13.7"` -> `version: "v13.7.0"`

**Comment by nakabonne** [comment]
@nghialv I thought we can allow the difference in patch-level. According to [Helm Best Practices](https://helm.sh/docs/chart_best_practices/dependencies/#versions), I settled on using patch-level version match. But no strong opinion, okay let me fix the versions in Chart.yaml.

**Comment by nghialv** [comment]
Yes, that is the ideal case. But we are using GitOps so I think everything should be immutable.

**Comment by nakabonne** [comment]
@nghialv I feel the same way. I've gotten stuff done!

**Pull request merged**
