### PR TITLE
Use deploying field for application sync status displaying

### PR DESCRIPTION
**Pull request by cakecatz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Refs #1369

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
@cakecatz Nice. Thank you. I just want to confirm its behavior.


| app.deploying | app.syncState.status              | Shown Icon  |
|---------------|-----------------------------------|-------------|
| true          | ApplicationSyncStatus.SYNCED      | DEPLOYING   |
| true          | ApplicationSyncStatus.OUT_OF_SYNC | DEPLOYING   |
| true          | ApplicationSyncStatus.UNKNOWN     | DEPLOYING   |
| true          | ApplicationSyncStatus.DEPLOYING   | DEPLOYING   |
| false         | ApplicationSyncStatus.SYNCED      | SYNCED      |
| false         | ApplicationSyncStatus.OUT_OF_SYNC | OUT_OF_SYNC |
| false         | ApplicationSyncStatus.UNKNOWN     | N/A         |
| false         | ApplicationSyncStatus.DEPLOYING   | DEPLOYING   |

Is this correct?

**Comment by cakecatz** [comment]
@nghialv That is almost correct.

`ApplicationSyncStatus.UNKNOWN` also displays the icon.

image
`unknown, synced, deploying, out of sync`

**Comment by nghialv** [comment]
So this is what we are expecting, right?


| app.deploying | app.syncState.status              | Shown Icon  | Shown Title |
|---------------|-----------------------------------|-------------|---|
| true          | ApplicationSyncStatus.SYNCED      | deploying   | Deploying |
| true          | ApplicationSyncStatus.OUT_OF_SYNC | deploying   | Deploying |
| true          | ApplicationSyncStatus.UNKNOWN     | deploying   | Deploying |
| true          | ApplicationSyncStatus.DEPLOYING   | deploying   | Deploying |
| false         | ApplicationSyncStatus.SYNCED      | synced      | Synced |
| false         | ApplicationSyncStatus.OUT_OF_SYNC | out_of_sync | Out of Sync |
| false         | ApplicationSyncStatus.UNKNOWN     | unknown         | Unknown |
| false         | ApplicationSyncStatus.DEPLOYING   | deploying   | Deploying |

**Comment by nghialv** [comment]
Looks good. Thank you.
/lgtm

**Comment by khanhtc1202** [comment]
🚀 🚀 🚀 
/approve

**Pull request merged**
