### PR TITLE
Allow configuring additional flags for Terraform commands

### LINKED ISSUE #2728: Terraform backend-config option
We are trying to use pipecd to manage to terraform. It seems that there are no options we can give `-backend-config` (we are using this option) option to `terraform init` other than `-var` and `-var-file`.

Do you plan to add configs to accept backend config options to TerraformApp?

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2728

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by ono-max — COMMENTED** [review]
Nice.
/lgtm

**Comment by khanhtc1202** [comment]
Nice
/approve

**Pull request merged**
