### PR TITLE
Add description about event watcher

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
👍 
/approve

**Comment by khanhtc1202** [comment]
確かにw

**Comment by nghialv** [comment]
Chuẩn!

**Comment by nakabonne** [comment]
Tốt nhỉ.

**Pull request merged**
