### PR TITLE
Add contributor list to readme

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
So fancy!
image

**Comment by nakabonne** [comment]
One thing, I'm a little bit worried about how to manage this list. Do we have to update this list whenever new contributor comes?

**Comment by nghialv** [comment]
For this time, I think updating the list one per month is still good. (Having a script to generate that list could be needed in the future.)

**Comment by nakabonne** [comment]
Okay, I feel you. Let's automate when needed!
/approve

**Pull request merged**
