### PR TITLE
Add Namespace kind to the default watching list of Kubernetes

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes part of #2436

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Nice.
/lgtm

**Comment by nakabonne** [comment]
@ono-max We automatically squash before merging, so you don't have to force-push 👍

**Comment by ono-max** [comment]
Wow, that's good. Thank you for teaching me 👍

**Pull request merged**
